# # Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'
#
# # Inserts a blank line between shell prompts
# add_newline = true
#
# # Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
#
# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true
# ~/.config/starship.toml

# Use custom format
format = '$all'


# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'

[[battery.display]]
threshold = 10
style = 'bold red'


[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vimcmd_symbol = "[|N|](bold green) "
vimcmd_replace_symbol = "[R](bold yellow) "
vimcmd_visual_symbol = "[V](bold purple) "
