alias aliases="nvim ~/.oh-my-zsh/custom/aliases.zsh"
alias vi="nvim"
alias vim="nvim"
alias zshrc="nvim ~/.zshrc"
alias bashrc="nvim ~/.bashrc"
alias bashprofile="nvim ~/.bash_profile"
alias starshipconfig="nvim ~/.config/starship/starship.toml"
alias aerospaceconfig='nvim ~/aerospace.toml'
alias lsa="eza --long --header --icons --all"
